CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "IDNumber" text NOT NULL,
        "DateOfBirth" timestamp with time zone NOT NULL,
        "Address" text NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "DeletedAt" timestamp with time zone,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "AuditLogs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "UserEmail" text NOT NULL,
        "Action" text NOT NULL,
        "EntityType" text NOT NULL,
        "EntityId" text NOT NULL,
        "Details" text NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "IpAddress" text NOT NULL,
        "UserAgent" text NOT NULL,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "Notifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "Title" text NOT NULL,
        "Message" text NOT NULL,
        "Type" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsRead" boolean NOT NULL,
        "RelatedLoanId" integer,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "SystemSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MaxLoanAmount" numeric(18,2) NOT NULL,
        "MaxLoanTermMonths" integer NOT NULL,
        "SmallLoanBaseRate" numeric NOT NULL,
        "MediumLoanBaseRate" numeric NOT NULL,
        "LargeLoanBaseRate" numeric NOT NULL,
        "MinimumInterestRate" numeric NOT NULL,
        "MaximumInterestRate" numeric NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "UpdatedByUserId" text,
        "UpdatedByEmail" text,
        CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "Loans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "BorrowerId" text NOT NULL,
        "PrincipalAmount" numeric(18,2) NOT NULL,
        "InterestRate" numeric(5,2) NOT NULL,
        "TermMonths" integer NOT NULL,
        "TotalRepayable" numeric(18,2) NOT NULL,
        "MonthlyInstallment" numeric(18,2) NOT NULL,
        "Purpose" text NOT NULL,
        "Status" integer NOT NULL,
        "ApplicationDate" timestamp with time zone NOT NULL,
        "ApprovalDate" timestamp with time zone,
        "StartDate" timestamp with time zone,
        "EndDate" timestamp with time zone,
        "ApprovedBy" text,
        "InitiationFee" numeric(18,2) NOT NULL,
        "MonthlyServiceFee" numeric(18,2) NOT NULL,
        "MonthlyCreditLifePremium" numeric(18,2) NOT NULL,
        "TotalInterest" numeric(18,2) NOT NULL,
        "TotalFees" numeric(18,2) NOT NULL,
        "ApplicationMethod" integer NOT NULL,
        "DocumentsVerified" boolean NOT NULL,
        "AffordabilityAssessed" boolean NOT NULL,
        "CreditCheckCompleted" boolean NOT NULL,
        "NCACompliant" boolean NOT NULL,
        CONSTRAINT "PK_Loans" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Loans_AspNetUsers_BorrowerId" FOREIGN KEY ("BorrowerId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "AffordabilityAssessments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "MonthlyGrossIncome" numeric(18,2) NOT NULL,
        "MonthlyNetIncome" numeric(18,2) NOT NULL,
        "MonthlyRentOrBond" numeric(18,2) NOT NULL,
        "MonthlyLivingExpenses" numeric(18,2) NOT NULL,
        "MonthlyDebtObligations" numeric(18,2) NOT NULL,
        "MonthlyInsurance" numeric(18,2) NOT NULL,
        "OtherExpenses" numeric(18,2) NOT NULL,
        "TotalMonthlyExpenses" numeric(18,2) NOT NULL,
        "DisposableIncome" numeric NOT NULL,
        "DebtToIncomeRatio" numeric NOT NULL,
        "CanAffordLoan" boolean NOT NULL,
        "AffordabilityNotes" text,
        "AssessmentDate" timestamp with time zone NOT NULL,
        "AssessedBy" text,
        CONSTRAINT "PK_AffordabilityAssessments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AffordabilityAssessments_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "CreditChecks" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "CreditBureau" text,
        "CreditScore" integer,
        "CreditScoreRating" text,
        "HasAdverseListings" boolean NOT NULL,
        "IsUnderDebtReview" boolean NOT NULL,
        "HasPreviousDefaults" boolean NOT NULL,
        "NumberOfCreditAccounts" integer NOT NULL,
        "Status" integer NOT NULL,
        "Notes" text,
        "CheckDate" timestamp with time zone NOT NULL,
        "CheckedBy" text,
        CONSTRAINT "PK_CreditChecks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CreditChecks_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "LoanDocuments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "FileName" text NOT NULL,
        "FileUrl" text NOT NULL,
        "FileType" text NOT NULL,
        "FileSize" bigint NOT NULL,
        "DocumentType" integer NOT NULL,
        "Status" integer NOT NULL,
        "UploadedDate" timestamp with time zone NOT NULL,
        "UploadedBy" text,
        "IsVerified" boolean NOT NULL,
        "VerifiedDate" timestamp with time zone,
        "VerifiedBy" text,
        "VerificationNotes" text,
        CONSTRAINT "PK_LoanDocuments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_LoanDocuments_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE TABLE "Repayments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "LoanId" integer NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "PaymentDate" timestamp with time zone NOT NULL,
        "TransactionReference" text NOT NULL,
        "Status" integer NOT NULL,
        CONSTRAINT "PK_Repayments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Repayments_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    INSERT INTO "SystemSettings" ("Id", "LargeLoanBaseRate", "MaxLoanAmount", "MaxLoanTermMonths", "MaximumInterestRate", "MediumLoanBaseRate", "MinimumInterestRate", "SmallLoanBaseRate", "UpdatedAt", "UpdatedByEmail", "UpdatedByUserId")
    VALUES (1, 22.0, 100000.0, 60, 27.5, 24.0, 18.0, 27.5, TIMESTAMPTZ '2025-11-11T11:44:15.468874Z', NULL, NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_AffordabilityAssessments_LoanId" ON "AffordabilityAssessments" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE INDEX "IX_AuditLogs_Timestamp_Action" ON "AuditLogs" ("Timestamp", "Action");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE UNIQUE INDEX "IX_CreditChecks_LoanId" ON "CreditChecks" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE INDEX "IX_LoanDocuments_LoanId_DocumentType" ON "LoanDocuments" ("LoanId", "DocumentType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE INDEX "IX_Loans_BorrowerId_Status" ON "Loans" ("BorrowerId", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE INDEX "IX_Notifications_UserId_IsRead" ON "Notifications" ("UserId", "IsRead");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    CREATE INDEX "IX_Repayments_LoanId_PaymentDate" ON "Repayments" ("LoanId", "PaymentDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    PERFORM setval(
        pg_get_serial_sequence('"SystemSettings"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "SystemSettings") + 1,
            nextval(pg_get_serial_sequence('"SystemSettings"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111114421_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251111114421_InitialPostgres', '8.0.8');
    END IF;
END $EF$;
COMMIT;

